# Generated by Django 5.1.2 on 2024-12-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_quizmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='quiz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
