# Generated by Django 5.1.2 on 2024-12-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_quizmodel_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='quiz',
        ),
    ]
