# Generated by Django 5.1.2 on 2024-10-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningModel',
            new_name='CourseModel',
        ),
    ]
