# Generated by Django 5.1.2 on 2024-12-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
