# Generated by Django 5.1.2 on 2024-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_rename_learningmodel_coursemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='image',
            field=models.URLField(),
        ),
    ]
