# Generated by Django 5.1.2 on 2024-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_coursemodel_price_alter_categorymodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='categories',
            field=models.ManyToManyField(to='learning.categorymodel'),
        ),
    ]
