# Generated by Django 5.1.2 on 2024-10-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_remove_coursemodel_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.categorymodel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
