# Generated by Django 5.1.2 on 2024-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_coursemodel_category_alter_coursemodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='categories',
            field=models.ManyToManyField(to='learning.categorymodel'),
        ),
    ]
