# Generated by Django 5.1.2 on 2024-10-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_cartitem_remove_ordermodel_user_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
