# Generated by Django 5.1.2 on 2024-10-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_exammodel_answermodel_modulemodel_exammodel_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='parent_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_modules', to='learning.parentmodule'),
        ),
    ]
